# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_word_furigana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='furigana',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
