# runtime: python
# env: flex
# entrypoint: gunicorn -b :$PORT j_renshuu_api.wsgi:application

# runtime_config:
#   python_version: 3

# handlers:

# - url: /(.+)
#   script: j_renshuu_api.wsgi:application


# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT j_renshuu_api.wsgi:application

beta_settings:
    cloud_sql_instances: "j-renshuu-api:asia-east1:j-renshuu"

runtime_config:
  python_version: 3
# [END runtime]